In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display

In [29]:
file_path = r"G:\My Drive\New_Working_Files\KNIME\CTU_2026\ML\Water_fall.csv"
def generate_performance_report(file_path, week_start, week_end):
    df = pd.read_csv(file_path)
    for col in ['weekly_gmv', 'marketing_spend']:
        df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)/1e6
    df['weekly_ROI'] = pd.to_numeric(df['weekly_ROI'], errors='coerce').fillna(0)

    results = []
    categories = df['analytic_category'].unique()

    for cat in categories:
        data = df[df['analytic_category']== cat]
        try:
            base = data[data['week_num'] == week_start].iloc[0]
            current = data[data['week_num'] == week_end].iloc[0]

            total_change = current['weekly_gmv'] - base['weekly_gmv']
            mkt_impact = (current['marketing_spend'] - base['marketing_spend']) * base['weekly_ROI']
            organic = total_change - mkt_impact

            results.append({
                'Category': cat,
                'Total_Change': total_change,
                'Marketing_Impact': mkt_impact,
                'Organic_Growth': organic,
                'Start_GMV': base['weekly_gmv'],
                'End_GMV':  current['weekly_gmv']
            })
        except Exception as e:
            continue 
    
    perf_df = pd.DataFrame(results).sort_values('Total_Change', ascending=False)
    top_3 = perf_df.head(3)
    worst_3 = perf_df.tail(3)

    print(f"\n ---- Top 3 Performers (wk {week_start} to {week_end})----")
    display(perf_df.head(3))
    
    print(f"\n---- Top Worst performers  (wk {week_start} to {week_end})---")
    display(perf_df.tail(3))
   

csv_path = r"G:\My Drive\New_Working_Files\KNIME\CTU_2026\ML\Water_fall.csv"
generate_performance_report(csv_path, 2,3)

 ---- Top 3 Performers (wk 2 to 3)----

,Category,Total_Change,Marketing_Impact,Organic_Growth,Start_GMV,End_GMV
119,Mobile,11705.776441,28674.644856,-16968.868415,9038.009899,20743.786340
81,Laptops,1958.035972,6710.835284,-4752.799312,598.332070,2556.368042
212,Television,1092.614657,4692.897527,-3600.282870,581.600465,1674.215122

---- Top Worst performers  (wk 2 to 3)---

,Category,Total_Change,Marketing_Impact,Organic_Growth,Start_GMV,End_GMV
142,Seasonal,-68.103537,29.761694,-97.865231,358.147449,290.043912
117,MensWinterwearUB,-122.960760,-95.191859,-27.768901,335.643580,212.682820
230,WomenWesternCore,-123.677423,-48.294743,-75.382680,739.875814,616.198391